# Generated by Django 3.1.6 on 2021-03-01 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EventTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateTimeField()),
                ('notes', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_tasks', to='assistapp.event')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_tasks', to='assistapp.priority')),
            ],
        ),
    ]
