# Generated by Django 3.1.6 on 2021-03-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistapp', '0002_auto_20210302_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtask',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
