# Generated by Django 3.1.6 on 2021-03-02 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistapp', '0003_auto_20210302_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtask',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tasks', to='assistapp.event'),
        ),
    ]
