# Generated by Django 3.1.6 on 2021-03-03 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistapp', '0004_auto_20210302_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 15, 2, 14, 928275)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 15, 2, 14, 928275)),
        ),
    ]
