# Generated by Django 3.1.6 on 2021-03-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistapp', '0005_auto_20210303_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default='2021-03-04T10:53:29Z'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default='2021-03-04T10:53:29Z'),
        ),
        migrations.AlterField(
            model_name='eventtask',
            name='due_date',
            field=models.DateTimeField(default='2021-03-04T10:53:29Z'),
        ),
    ]
