# Generated by Django 3.1.6 on 2021-03-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistapp', '0007_auto_20210304_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default='2021-03-04T10:56:52Z'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default='2021-03-04T10:56:52Z'),
        ),
        migrations.AlterField(
            model_name='eventtask',
            name='due_date',
            field=models.DateTimeField(default='2021-03-04T10:56:52Z'),
        ),
    ]
