# Generated by Django 3.1.6 on 2021-03-04 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistapp', '0008_auto_20210304_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 57, 30, 773174)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 57, 30, 773174)),
        ),
        migrations.AlterField(
            model_name='eventtask',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 57, 30, 774174)),
        ),
    ]
