# Generated by Django 3.1.6 on 2021-03-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistapp', '0010_auto_20210304_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtask',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
